exchangers:
  process_exchanger:
    name: "process_exchanger"  # Название обменника
    type: "direct"  # Тип обменника
    queues:
      - "youtube"  # Очередь для обработки данных YouTube
      - "storage"  # Очередь для обработки данных storage
      - "google_drive"

consumers:
  youtube_consumer:
    exchanger: "exchangers.process_exchanger"  # Ссылка на обменник из секции exchangers
    queue: "youtube"  # Очередь, которую будет обрабатывать consumer
    routing_key: "youtube"  # Ключ маршрутизации для обменника

  storage_consumer:
    exchanger: "exchangers.process_exchanger"  # Ссылка на обменник из секции exchangers
    queue: "storage"  # Очередь, которую будет обрабатывать consumer
    routing_key: "storage"  # Ключ маршрутизации для обменника

  google_drive_consumer:
    exchanger: "exchangers.process_exchanger"  # Ссылка на обменник из секции exchangers
    queue: "google_drive"  # Очередь, которую будет обрабатывать consumer
    routing_key: "google_drive"  # Ключ маршрутизации для обменника

