"""Initial migration

Revision ID: ee395199f4d7
Revises: 
Create Date: 2024-05-21 11:25:52.089355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee395199f4d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assistants',
    sa.Column('assistant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assistant', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('assistant_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_for_chunks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('assistant_id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.CHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('format_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcribed_texts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('initiator_user_id', sa.BigInteger(), nullable=False),
    sa.Column('transcription_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('transcription_time', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('format_id', sa.Integer(), nullable=False),
    sa.Column('duration', postgresql.INTERVAL(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['format_id'], ['formats.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('cost_per_token', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_texts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('transcribed_text_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('summary_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['transcribed_text_id'], ['transcribed_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.BigInteger(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('error_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['ai_assistants.assistant_id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_statuses')
    op.drop_table('summary_texts')
    op.drop_table('pricing')
    op.drop_table('files')
    op.drop_table('transcribed_texts')
    op.drop_table('statuses')
    op.drop_table('stages')
    op.drop_table('sources')
    op.drop_table('models')
    op.drop_table('formats')
    op.drop_table('currencies')
    op.drop_table('ai_assistants')
    # ### end Alembic commands ###
